// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDupVFl8zfswhzLeIdq200XdjCCo_Lyflo',
    appId: '1:18227755258:web:ffec6baa3fb6747dca3143',
    messagingSenderId: '18227755258',
    projectId: 'quantumphysics-508ce',
    authDomain: 'quantumphysics-508ce.firebaseapp.com',
    storageBucket: 'quantumphysics-508ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVMG9q9GRTK9SXUKGly6_a2OizO0vyj0',
    appId: '1:18227755258:android:338cf2b6fb430c26ca3143',
    messagingSenderId: '18227755258',
    projectId: 'quantumphysics-508ce',
    storageBucket: 'quantumphysics-508ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0FDYJ3j3OIp6UAMRSeQ6JdJzooGJRaQ',
    appId: '1:18227755258:ios:ca4c19e1de10bbd3ca3143',
    messagingSenderId: '18227755258',
    projectId: 'quantumphysics-508ce',
    storageBucket: 'quantumphysics-508ce.firebasestorage.app',
    iosBundleId: 'com.example.easyquantum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0FDYJ3j3OIp6UAMRSeQ6JdJzooGJRaQ',
    appId: '1:18227755258:ios:ca4c19e1de10bbd3ca3143',
    messagingSenderId: '18227755258',
    projectId: 'quantumphysics-508ce',
    storageBucket: 'quantumphysics-508ce.firebasestorage.app',
    iosBundleId: 'com.example.easyquantum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDupVFl8zfswhzLeIdq200XdjCCo_Lyflo',
    appId: '1:18227755258:web:d0a3d46897e6dc49ca3143',
    messagingSenderId: '18227755258',
    projectId: 'quantumphysics-508ce',
    authDomain: 'quantumphysics-508ce.firebaseapp.com',
    storageBucket: 'quantumphysics-508ce.firebasestorage.app',
  );
}
